import {Box,CheckCircle2,ChevronRight,Cloud,Code2,Cpu,Database,FileCode2,FileJson,Folder,Globe2,HardHat,KeyRound,Radio,Search,Server,ShieldCheck,Workflow} from 'lucide-react'
import {scenes} from '../../data/scenes'
import {hardhatTrace as trace} from '../../data/traces/hardhatTrace'
import type {Scene,Network as NetworkMode} from '../../types/scenes'

type Props={scene:Scene;index:number;network:NetworkMode;onInspect:(id:string)=>void}
export function AnimationStage({network,onInspect}:Props){return <section className="cinema-stage"><div className="film-grain"/>{scenes.map((scene,i)=><article className={`cinematic-scene shot-${kind(i)}`} data-cinematic-index={i} key={scene.id}><svg className={`shot-route ${['RPC','TX','SIGNED TX','RECEIPT','RESPONSE'].includes(scene.packet)?'transfer-route':''}`} viewBox="0 0 1200 650" preserveAspectRatio="none"><path className="cinematic-route" d={route(i)}/></svg><div className="scene-packet">{scene.packet}</div><Shot index={i} network={network} inspect={onInspect}/><div className="shot-slug"><span>CHAPTER {String(i+1).padStart(2,'0')}</span><b>{scene.short}</b></div></article>)}</section>}

function Shot({index,network,inspect}:{index:number;network:NetworkMode;inspect:(id:string)=>void}){
 if(index<=1)return <Editor inspect={inspect} inspection={index===1}/>
 if(index===2)return <TerminalShot command={trace.buildCommand} output="Press Enter to go inside Hardhat"/>
 if(index===3)return <ConfigShot inspect={inspect}/>
 if(index===4)return <DiscoveryShot/>
 if(index===5)return <CompilerShot output={false}/>
 if(index===6)return <CompilerShot output/>
 if(index===7)return <FilesystemShot inspect={inspect}/>
 if(index===8)return <LocalBoot/>
 if(index===9)return <DeploymentShot inspect={inspect}/>
 if(index===10)return <TransactionShot signed={false} publicNet={false} inspect={inspect}/>
 if(index===11)return <SigningShot/>
 if(index===12)return <RpcShot remote={false}/>
 if(index===13)return <BlockShot publicNet={false}/>
 if(index===14)return <EvmShot call={false}/>
 if(index===15)return <StateShot publicNet={false} count={0} inspect={inspect}/>
 if(index===16)return <ReceiptShot/>
 if(index===17)return <InteractionShot read={false}/>
 if(index===18)return <EvmShot call/>
 if(index===19)return <InteractionShot read/>
 if(index===20)return <SepoliaCommand/>
 if(index===21)return <ComparisonShot/>
 if(index===22)return <TransactionShot signed publicNet inspect={inspect}/>
 if(index===23)return <LeaveComputer/>
 if(index===24)return <AlchemyShot/>
 if(index===25)return <PublicNodeShot/>
 if(index===26)return <MempoolShot/>
 if(index===27)return <ConsensusShot validation={false}/>
 if(index===28)return <ConsensusShot validation/>
 if(index===29)return <BlockShot publicNet/>
 if(index===30)return <EvmShot call={false}/>
 if(index===31)return <StateShot publicNet count={0} inspect={inspect}/>
 if(index===32)return <ExplorerShot inspect={inspect}/>
 if(index===33)return <VerifyShot/>
 return <RecapShot network={network}/>
}

const Title=({kicker,title,children}:{kicker:string;title:string;children?:React.ReactNode})=><div className="shot-title"><small>{kicker}</small><h2>{title}</h2>{children&&<p>{children}</p>}</div>
const Step=({icon,children,active=false}:{icon?:React.ReactNode;children:React.ReactNode;active?:boolean})=><div className={`process-item process-step ${active?'process-active':''}`}>{icon}<span>{children}</span></div>
const Inspect=({id,fn,label='INSPECT'}:{id:string;fn:(id:string)=>void;label?:string})=><button className="inspect-action" onClick={()=>fn(id)}>{label} <ChevronRight/></button>

function Editor({inspect,inspection}:{inspect:(id:string)=>void;inspection:boolean}){return <div className="ide-world"><Title kicker="01 / VS CODE" title={inspection?'Before Compilation':'Watch Counter.sol Be Written'}>{inspection?'The file is still only human-readable source.':'A stateful Solidity program begins as text.'}</Title><div className="ide"><aside><b>EXPLORER</b><span><Folder/> contracts</span><span className="selected"><FileCode2/> Counter.sol</span></aside><section><header>Counter.sol <i>●</i></header><pre className={inspection?'':'type-reveal'}><em>// SPDX-License-Identifier: MIT</em>{'\n'}<b>pragma</b> solidity ^0.8.34;{'\n\n'}<b>contract</b> Counter {'{'}{'\n'}  <mark>uint256 public count;</mark>{'\n\n'}  <b>function</b> increment() public {'{'}{'\n'}    count++;{'\n'}  {'}'}{'\n\n'}  <b>function</b> setCount(uint256 newCount) public {'{'}{'\n'}    count = newCount;{'\n'}  {'}'}{'\n'}{'}'}</pre></section></div>{inspection?<div className="missing-strip"><span>NO ABI</span><span>NO BYTECODE</span><span>NO ADDRESS</span><span>NO BLOCKCHAIN STATE</span></div>:<div className="code-notes"><Step>uint256 → unsigned 256-bit integer</Step><Step>public → compiler generates count()</Step><Step active>increment() changes persistent count</Step></div>}<Inspect id="source" fn={inspect} label="INSPECT SOURCE"/></div>}
function TerminalShot({command,output}:{command:string;output:string}){return <div className="terminal-world"><Title kicker="TERMINAL / REAL COMMAND" title="Start Hardhat 3.15.0">The camera is about to enter the build pipeline.</Title><div className="hero-terminal"><header><i/><i/><i/> reference-hardhat — zsh</header><code><b>$</b> <span className="type-reveal">{command}</span><br/><em>{output}</em><br/><strong>Hardhat v{trace.version}</strong></code></div><div className="dive-ring"><HardHat/> ENTER BUILD SYSTEM</div></div>}
function ConfigShot({inspect}:{inspect:(id:string)=>void}){return <div className="config-world"><Title kicker="INSIDE HARDHAT" title="Files Open. Settings Are Extracted."/><div className="config-sheet process-active"><header><FileJson/> hardhat.config.ts</header><pre>plugins: [hardhatToolboxMochaEthersPlugin]{'\n'}solidity.profiles.default.version: <mark>&quot;0.8.34&quot;</mark>{'\n'}production.optimizer: <mark>enabled · 200 runs</mark>{'\n'}localhost: <mark>http://127.0.0.1:8545</mark>{'\n'}sepolia: <mark>configVariable(...)</mark></pre></div><div className="extracted"><Step>PLUGIN</Step><Step>COMPILER PROFILE</Step><Step>NETWORK DEFINITIONS</Step><Step>RPC + ACCOUNT REFERENCES</Step></div><Inspect id="config" fn={inspect}/></div>}
function DiscoveryShot(){return <div className="discovery-world"><Title kicker="BUILD PIPELINE / DISCOVERY" title="What Does Hardhat Read?">This real contract has no Solidity imports, so its source graph contains one project file.</Title><div className="file-orbit"><Step icon={<FileJson/>}>hardhat.config.ts</Step><Step icon={<Folder/>}>contracts/</Step><Step icon={<FileCode2/>} active>contracts/Counter.sol</Step><Step icon={<Workflow/>}>imports: none</Step></div><div className="job-ticket"><small>COMPILATION JOB</small><b>Counter.sol</b><span>compiler 0.8.34 · profile default · EVM osaka</span></div></div>}
function CompilerShot({output}:{output:boolean}){return <div className="factory-world"><Title kicker="HARDHAT BUILD PIPELINE" title={output?'Compiler Outputs Are Manufactured':'Source Enters solc 0.8.34'}>{trace.compileRelationship}; this is one build pipeline, not two fake factories.</Title><div className="conveyor"><div className="inputs"><Step>Counter.sol</Step><Step>compiler input JSON</Step><Step>profile: default</Step><Step>EVM: osaka</Step></div><div className="compiler-core process-active"><Cpu/><b>SOLC</b><strong>{trace.compiler}</strong><i/><i/><i/></div><div className="outputs">{output?<><Step>ABI</Step><Step>CREATION BYTECODE</Step><Step>RUNTIME BYTECODE</Step><Step>OPCODES + SOURCE MAPS</Step><Step>METHOD IDENTIFIERS</Step></>:<><Step>source parsing</Step><Step>semantic checks</Step><Step>EVM output generation</Step></>}</div></div>{output&&<div className="bytecode-compare"><code>{trace.creationBytecode}</code><b>CREATES ACCOUNT</b><span>≠</span><code>{trace.runtimeBytecode}</code><b>STORED AT ADDRESS</b></div>}</div>}
function FilesystemShot({inspect}:{inspect:(id:string)=>void}){return <div className="filesystem-world"><Title kicker="AFTER npx hardhat build" title="The Filesystem Changes">These are the exact output paths written by Hardhat 3.15.0.</Title><div className="file-tree">{trace.generated.map((f,i)=><div className={`process-item ${i===2?'process-active':''}`} key={f}><FileCode2/><span>{f}</span></div>)}</div><div className="artifact-open"><small>Counter.json</small>{trace.artifactKeys.slice(0,8).map(k=><code key={k}>&quot;{k}&quot;</code>)}</div><div className="inspect-group"><Inspect id="artifacts" fn={inspect} label="INSPECT ARTIFACT"/><Inspect id="artifacts" fn={inspect} label="INSPECT ABI"/></div></div>}
function LocalBoot(){return <div className="boot-world"><Title kicker="LOCAL DEVELOPMENT SIMULATION" title="A Local Ethereum Runtime Powers On"/><div className="boot-terminal"><code>$ npx hardhat node</code><strong>Started HTTP and WebSocket JSON-RPC server at {trace.rpc}</strong></div><div className="boot-sequence"><Step icon={<Radio/>}>RPC listener · 127.0.0.1:8545</Step><Step icon={<KeyRound/>}>20 development accounts</Step><Step icon={<Database/>}>genesis state + 10,000 ETH balances</Step><Step icon={<Cpu/>} active>EDR execution + automining</Step></div><div className="accounts-film">{trace.accounts.map(a=><span key={a.address}>{a.address.slice(0,10)}… <b>{a.balance}</b></span>)}</div></div>}
function DeploymentShot({inspect}:{inspect:(id:string)=>void}){return <div className="deployment-world"><Title kicker="IGNITION / FILES ACTUALLY USED" title="Prepare the Counter Deployment"/><div className="module-code process-active"><header>ignition/modules/Counter.ts</header><pre>buildModule(&quot;CounterModule&quot;, (m) =&gt; {'{'}{'\n'}  const counter = <mark>m.contract(&quot;Counter&quot;)</mark>;{'\n'}  return {'{'} counter {'}'};{'\n'}{'}'});</pre></div><div className="artifact-vault"><Box/><b>Counter.json opens</b><Step>ABI extracted</Step><Step>creation bytecode extracted</Step></div><Inspect id="deploy" fn={inspect}/></div>}
function TransactionShot({signed,publicNet,inspect}:{signed:boolean;publicNet:boolean;inspect:(id:string)=>void}){return <div className="assembly-world"><Title kicker="TRANSACTION ASSEMBLY" title={signed?'Sepolia Transaction Built Locally':'Build the Creation Transaction'}>Counter.sol never leaves the computer. Creation bytecode is inserted into data.</Title><div className="transaction-shell process-active"><header>{signed?'SIGNED TYPE-2 TRANSACTION':'ETHEREUM TRANSACTION'}</header><Step>chainId <b>{publicNet?'11155111 · Sepolia':'31337 · Local'}</b></Step><Step>nonce <b>0</b></Step><Step>maxFeePerGas <b>{publicNet?'network estimate':'0xb2d05e00'}</b></Step><Step>gasLimit <b>105339</b></Step><Step>value <b>0 ETH</b></Step><Step>to <b className="null">EMPTY · CREATE</b></Step><Step active>data <code>{trace.creationBytecode}</code></Step></div><Inspect id="tx" fn={inspect} label="INSPECT TRANSACTION"/></div>}
function SigningShot(){return <div className="sign-world"><Title kicker="AUTHORIZATION" title="Unsigned → Signed → Serialized">The reference account is identified, but its private key is deliberately never displayed.</Title><div className="sign-line"><Step>UNSIGNED TRANSACTION</Step><ChevronRight/><div className="signer process-active"><KeyRound/><b>SIGNER</b><span>0xf39fd6e5…</span><i>ECDSA</i></div><ChevronRight/><Step>SIGNED TRANSACTION</Step><ChevronRight/><Step>0x02f8… SERIALIZED</Step></div></div>}
function RpcShot({remote}:{remote:boolean}){return <div className="rpc-world"><Title kicker={remote?'REMOTE JSON-RPC':'LOCAL JSON-RPC'} title="Provider Creates a Real RPC Request">{remote?'A serialized signed transaction will leave the computer.':'Ignition used the unlocked local account via eth_sendTransaction; the request stays inside this machine.'}</Title><div className="provider-machine"><Code2/><b>PROVIDER</b><span>construct request</span></div><div className="json-envelope process-active"><code>{'{'}{`\n  "jsonrpc": "2.0",\n  "method": "${remote?trace.deployment.remoteRpcMethod:trace.deployment.localRpcMethod}",\n  "params": [${remote?'"0x02f8…"':'{ from, data }'}]\n`}{'}'}</code></div><div className="local-boundary"><b>YOUR COMPUTER</b><Radio/><strong>{trace.rpc}</strong><span>NOTHING LEFT THIS COMPUTER</span></div></div>}
function BlockShot({publicNet}:{publicNet:boolean}){return <div className="block-world"><Title kicker={publicNet?'SEPOLIA BLOCK':'LOCAL AUTOMINING'} title={publicNet?'Our Transaction Enters a Public Block':'Block #1 Is Produced Immediately'}>{publicNet?'The accepted block opens and our creation transaction is located.':'Hardhat Network automines; this is not public proof-of-stake consensus.'}</Title><div className="block-forge process-active"><header>{publicNet?'SEPOLIA BLOCK #…':'BLOCK #1'}</header><small>parentHash</small><code>{publicNet?'0xb781…':'0x86100558…'}</code><div><b>TRANSACTION 0 · CONTRACT CREATION</b><span>from {trace.deployment.from.slice(0,12)}…</span><span>to CREATE</span><span>data 0x608060…</span><span>gas {trace.deployment.gasUsed}</span></div></div></div>}
function EvmShot({call}:{call:boolean}){return <div className="evm-world"><Title kicker="INSIDE THE EVM" title={call?'Runtime Bytecode Executes increment()':'Creation Bytecode Executes'}>{call?'Calldata selects a function, then persistent storage is read and written.':'Instructions run until creation code returns the runtime program.'}</Title><div className="instruction-stream">{(call?['PUSH4 d09de08a','EQ · JUMPI','SLOAD slot 0','PUSH1 01','ADD','SSTORE slot 0']:['PUSH1 80','PUSH1 40','MSTORE','CALLVALUE','CODECOPY','RETURN runtime']).map((op,i)=><code className={`process-item ${i===3?'process-active':''}`} key={op}>{op}</code>)}</div><div className="evm-core"><Cpu/><b>EVM</b><span>{call?'0 → +1 → 1':'creation code → runtime code'}</span></div><div className="evm-output"><small>OUTPUT</small><strong>{call?'SLOT 0 = 1':'RUNTIME BYTECODE'}</strong><code>{call?'SSTORE complete':trace.runtimeBytecode}</code></div></div>}
function StateShot({publicNet,count,inspect}:{publicNet:boolean;count:number;inspect:(id:string)=>void}){return <div className="state-world"><Title kicker={publicNet?'SEPOLIA STATE':'ETHEREUM STATE'} title="A Contract Account Is Written">This is account/state data—not Solidity source and not block history.</Title><div className="state-tree"><i/><i/><i/><div className="account-record process-active"><header>CONTRACT ACCOUNT</header><span>address <b>{publicNet?'0x742…':trace.deployment.address}</b></span><span>nonce <b>1</b></span><span>balance <b>0 ETH</b></span><span>code <code>{trace.runtimeBytecode}</code></span><div className="storage-cell"><small>STORAGE · SLOT 0</small><b>count</b><strong>{count}</strong></div></div></div><Inspect id={publicNet?'publicContract':'contract'} fn={inspect} label="INSPECT CONTRACT STATE"/></div>}
function ReceiptShot(){return <div className="receipt-world"><Title kicker="RPC RESPONSE / RETURN JOURNEY" title="The Result Comes Back"/><div className="receipt-paper process-active"><CheckCircle2/><b>TRANSACTION RECEIPT</b><span>transactionHash <code>{trace.deployment.transactionHash}</code></span><span>status <strong>1 · SUCCESS</strong></span><span>blockNumber <code>{trace.deployment.blockNumber}</code></span><span>gasUsed <code>{trace.deployment.gasUsed}</code></span><span>contractAddress <code>{trace.deployment.address}</code></span></div><div className="return-chain"><Step>NODE</Step><i>→</i><Step>JSON-RPC RESPONSE</Step><i>→</i><Step>PROVIDER</Step><i>→</i><Step>IGNITION</Step><i>→</i><Step>TERMINAL</Step></div></div>}
function InteractionShot({read}:{read:boolean}){return <div className="interaction-world"><Title kicker="scripts/interact.ts" title={read?'Read count() Without a Transaction':'Encode increment() With the ABI'}>{read?'eth_call simulates against current state and returns data.':'The ABI turns a function name into machine calldata.'}</Title><div className="interaction-code"><pre>const counter = await ethers.getContractAt(&quot;Counter&quot;, address);{'\n'}{read?'const value = await counter.count();':'await counter.increment();'}</pre></div><div className="encoder-film"><Step>{read?'count()':'increment()'}</Step><ChevronRight/><Step icon={<FileJson/>}>ABI lookup</Step><ChevronRight/><div className="process-item process-active"><b>{read?'eth_call':'0xd09de08a'}</b></div><ChevronRight/><Step>{read?'EVM state read → 1':'TO 0x5FbDB231…'}</Step></div>{read&&<div className="no-write"><span>NO SIGNATURE</span><span>NO MEMPOOL</span><span>NO BLOCK</span><span>NO STATE CHANGE</span></div>}</div>}
function SepoliaCommand(){return <div className="chapter-break"><span>LOCAL TEST COMPLETE</span><div className="chapter-line"/><Title kicker="NEW CHAPTER" title="Deploy to Sepolia"/><div className="hero-terminal"><code><b>$</b> npx hardhat ignition deploy ./ignition/modules/Counter.ts <mark>--network sepolia</mark></code></div><div className="resolved"><Step>SEPOLIA_RPC_URL → resolved, secret hidden</Step><Step>SEPOLIA_PRIVATE_KEY → signer, secret hidden</Step></div></div>}
function ComparisonShot(){return <div className="comparison-world"><Title kicker="LOCAL → PUBLIC" title="What Changes? What Stays the Same?"/><div className="compare-panels"><section><b>SAME</b>{['Counter artifact','creation bytecode','Ignition module','transaction structure','signing concept','EVM semantics'].map(x=><Step key={x}>{x}</Step>)}</section><section><b>DIFFERENT</b>{['chain ID','RPC endpoint','deployment wallet','fee market','peer propagation','proof-of-stake inclusion','public shared state'].map(x=><Step key={x}>{x}</Step>)}</section></div></div>}
function LeaveComputer(){return <div className="boundary-world"><Title kicker="THE CRITICAL BOUNDARY" title="The Transaction Actually Leaves Your Computer"/><div className="computer"><b>YOUR COMPUTER</b><Step>Hardhat + Ignition</Step><Step>ethers + signer</Step><Step>serialized 0x02f8…</Step><div className="port"><Radio/> eth_sendRawTransaction</div></div><div className="network-cable"><i/><i/><i/><Globe2/><span>HTTPS · INTERNET</span></div><div className="outside"><Cloud/><b>REMOTE INFRASTRUCTURE</b></div></div>}
function AlchemyShot(){return <div className="alchemy-world"><Title kicker="RPC PROVIDER · NOT THE BLOCKCHAIN" title="Alchemy Receives the HTTPS Request"/><div className="request-beam"><Step>HTTPS JSON-RPC</Step><ChevronRight/><div className="alchemy-gateway process-active"><Cloud/><b>ALCHEMY RPC ENDPOINT</b><code>method: eth_sendRawTransaction</code></div><ChevronRight/><Step>ETHEREUM NODE ACCESS</Step></div><div className="not-chain">ALCHEMY ≠ SEPOLIA ≠ THE BLOCKCHAIN</div></div>}
function PublicNodeShot(){return <div className="node-world"><Title kicker="REMOTE ETHEREUM NODE" title="The Node Does Work"/><div className="node-process"><Server/><div><Step>request received</Step><Step>transaction decoded</Step><Step>signature checked</Step><Step>basic validity checked</Step><Step active>accepted into local pending pool</Step></div></div><div className="hash-ticket"><small>IMMEDIATE RPC RESULT</small><b>TX HASH</b><code>0x9e21…counter…</code></div></div>}
function MempoolShot(){return <div className="mempool-world"><Title kicker="PEER-TO-PEER NETWORK" title="There Is No Single Global Mempool"/><div className="peer-field">{['NODE A','NODE B','NODE C','NODE D','NODE E','NODE F'].map((n,i)=><div className={`peer process-item ${i===2?'process-active':''}`} key={n}><Server/><b>{n}</b><small>local pending pool</small>{i===2&&<span>MY COUNTER DEPLOYMENT</span>}</div>)}</div><div className="gossip-lines">TRANSACTION GOSSIP → PEERS RELAY VALID DATA</div></div>}
function ConsensusShot({validation}:{validation:boolean}){return <div className="consensus-world"><Title kicker="ETHEREUM PROOF OF STAKE" title={validation?'Block Propagates and Validators Attest':'A Proposer Builds the Candidate Block'}/><div className="consensus-line">{validation?<><Step>candidate block</Step><ChevronRight/><Step>peer validation</Step><ChevronRight/><Step icon={<ShieldCheck/>} active>validator attestations</Step><ChevronRight/><Step>chain progresses / finality</Step></>:<><Step>pending transactions</Step><ChevronRight/><Step icon={<ShieldCheck/>} active>selected proposer</Step><ChevronRight/><Step>order transactions</Step><ChevronRight/><Step>candidate block</Step></>}</div><div className="accuracy-note">STANDARD ETHEREUM TRANSACTION · NO ACCOUNT ABSTRACTION LAYER</div></div>}
function ExplorerShot({inspect}:{inspect:(id:string)=>void}){return <div className="explorer-world"><Title kicker="EDUCATIONAL ETHERSCAN RECREATION" title="Connect the Explorer to What You Watched"/><div className="browser"><header><Search/><input readOnly value="0x742…"/><button>Search</button></header><nav>Overview · Transactions · Contract · Events</nav><section><div><small>CONTRACT ADDRESS</small><b>0x742…</b></div><div><small>BALANCE</small><b>0 ETH</b></div><div><small>CREATOR</small><b>0xf39… at txn 0x9e21…</b></div><div className="explorer-tx process-active"><b>Contract Creation</b><span>Status: Success</span><span>Block: #…</span><span>From: 0xf39…</span><span>To: [Contract Creation]</span><span>Gas: 105,339</span><code>Input: 0x6080604052…</code></div></section></div><Inspect id="address" fn={inspect} label="INSPECT ADDRESS"/></div>}
function VerifyShot(){return <div className="verify-world"><Title kicker="SEPARATE FROM DEPLOYMENT" title="Prove Which Source Matches On-Chain Bytecode"/><div className="verify-inputs"><Step>Counter.sol source</Step><Step>solc 0.8.34</Step><Step>compiler settings · EVM osaka</Step><Step>constructor arguments: none</Step><Step>build information</Step></div><div className="comparison-machine process-active"><Code2/><b>RECOMPILE</b><span>generated runtime bytecode</span><strong>=</strong><span>deployed on-chain bytecode</span></div><div className="verified"><CheckCircle2/><b>CONTRACT SOURCE VERIFIED</b><span>Deployment stored BYTECODE. Verification later proves the corresponding SOURCE.</span></div></div>}
function RecapShot({network}:{network:NetworkMode}){return <div className="recap-world"><Title kicker="FINAL RECAP" title="A Solidity File Became Ethereum State"/><div className="flashback-reel">{['Counter.sol typed','solc 0.8.34','ABI + bytecode','transaction assembled','signed 0x02f8…','JSON-RPC','peer propagation','block','EVM execution','contract state','Etherscan'].map((x,i)=><div className={`process-item f${i}`} key={x}>{x}</div>)}</div><div className="final-statement"><b>Counter.sol</b><span>became</span><b>EVM bytecode</b><span>which became</span><b>a deployed Ethereum contract</b><span>at</span><strong>{network==='local'?trace.deployment.address:'0x742…'}</strong></div></div>}
function kind(i:number){if(i<=1||i===17||i===19)return'editor';if(i===2||i===8||i===20)return'terminal';if(i>=23&&i<=30)return'network';if(i>=32)return'explorer';return'process'}
function route(i:number){if(i===16||i===19)return'M1030 170 C800 170 720 460 180 510';if(i===23||i===24)return'M180 470 C420 470 690 250 1050 210';return'M160 500 C390 470 660 270 1040 150'}
